#cloud-config
hostname: apache2
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIETSXcfvbkoDutKTxQA0c7AJiQt/IrrrzwqBjiNSRFF/ sroagar2111@sroagar2111
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text


